os: linux

language: cpp
compiler:
  - clang
  - gcc

install:
    - apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
      libjpeg-dev \
      libpng-dev \
      libglfw3-dev \
      libglm-dev \
      libx11-dev \
      libomp-dev \
      libegl1-mesa-dev \
      pkg-config

script:
    - ./build.sh --headless
